name: Build and Release

on:
  push:
    branches:
      - main  # Запуск при пуше в main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Установка зависимостей
        run: npm install

      - name: Сборка Electron-приложения
        run: npm run build

      - name: Автоматическое создание версии
        run: |
          git fetch --tags
          VERSION=$(git rev-parse --short HEAD)  # Используем хеш коммита как версию
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Запуск electron-builder
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder --win --publish always

      - name: Создание релиза на GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/*.exe
            dist/*.zip
            dist/latest.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
