name: Build and Release

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Установка зависимостей
        run: yarn install
        shell: pwsh

      - name: Получение версии из package.json
        id: package_version
        shell: pwsh
        run: |
          $version = (Get-Content package.json | ConvertFrom-Json).version
          echo "VERSION=$version" | Out-File -FilePath $env:GITHUB_ENV -Append

      - name: Создание и пуш тега
        shell: pwsh
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/IskenderDev/cartomat.git

          $tagExists = git tag --list "${{ env.VERSION }}"
          if ($tagExists) {
            Write-Host "Тег ${{ env.VERSION }} уже существует. Прерываем процесс."
            exit 1
          }

          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}

      - name: Запуск electron-builder
        shell: pwsh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder --win --publish always

      - name: Создание релиза на GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            dist/*.exe
            dist/latest.yml
            dist/*.exe.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
