name: Build and Release

on:
  push:
    branches:
      - main  # Запуск при пуше в main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Проверка GH_TOKEN
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: |
          if [ -z "$GH_TOKEN" ]; then
            echo "GH_TOKEN не установлен!"
            exit 1
          else
            echo "GH_TOKEN установлен."
          fi

      - name: Checkout репозитория
        uses: actions/checkout@v4

      - name: Установка Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Установка зависимостей
        run: npm install

      - name: Получение версии из package.json
        id: package_version
        run: echo "VERSION=$(node -p 'require(\"./package.json\").version')" >> $GITHUB_ENV

      - name: Проверка существующего тега
        run: |
          if git rev-parse "refs/tags/${{ env.VERSION }}" >/dev/null 2>&1; then
            echo "Тег уже существует. Прерываем процесс."
            exit 1
          fi

      - name: Создание и пуш тега
        run: |
          git tag ${{ env.VERSION }}
          git push origin ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}

      - name: Запуск electron-builder
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: npx electron-builder --win --publish always

      - name: Создание релиза на GitHub
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION }}
          name: Release ${{ env.VERSION }}
          draft: false
          prerelease: false
          files: |
            release/*.exe
            release/latest.yml
            release/*.exe.blockmap
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
